import ProofForge.Wasm.Host

/-!
# NEAR Protocol host contract

Historical proof_forge profile `near-wasm-raw-u64-v1` (docs/targets/03-near.md):

- import module `env` (NEAR runtime), not `host_lib` and not a generic `pf` module
- scalar params arrive as exactly `8 * paramCount` little-endian bytes via `env.input`
  (register 0); zero-arg methods require empty input; the bounded bytes/string extension uses
  canonical Borsh `u32_le(length) || active bytes`
- UInt64 slots persist as 8-byte little-endian values under ASCII field-name keys;
  bounded raw binary storage additionally exposes exact-key read/write/remove/has-key
- scalar views and mutating public results `value_return` 8-byte LE; bounded bytes/String and
  one-limb unsigned array views use canonical Borsh output through the guest arena; errors `panic_utf8`.
  This is **not** JSON ABI and **not** XRPL's C-param `i32`/`i64` export ABI.

The current profile uses all four storage calls plus `input` / `register_len` /
`read_register` / `value_return` / `panic_utf8`, context reads, and bounded static
`log_utf8`. Bounded bytes/string input is allocation-free; bounded view output and raw-storage
register copies use the checked guest arena. Raw storage preserves nearcore's exact 0/1 status,
stale-register, empty-value, and oversized-result behavior. The first detached Promise slice uses
static receiver/method literals, bounded arguments, lossless u128 deposit, and explicit gas through
the batch function-call ABI; explicit returned calls link the concrete receipt. Bounded callback
result reads preserve nearcore's 0/1/2 status, consult the register only on success, and expose
oversized lengths without copying. One static self-callback edge uses `promise_batch_then`, keeps
normal callback arguments separate from dependency results, and returns the callback receipt.
Promise joins and mutating bounded output stay fail closed.

The family `Wasm.Host.Contract` still describes XRPL's Data-blob import shape.
NEAR does not instantiate it; `Near.Emit` owns the env import table.
-/

namespace ProofForge.Wasm.Near.Host

def chainName : String := "near"

def digestDomain : String := "near-raw-u64|"

def headerTag : String := "PROOF-FORGE-NEAR-RAW-U64 v0"

def headerNotes : Array String := #[
  ";; Generated by ProofForge. Target: NEAR Protocol.",
  ";; Artifact: WAT → wasm. Host: `env` (near-wasm-raw-u64-v1).",
  ";; Storage: 8-byte LE UInt64 slots plus bounded exact-key raw binary access.",
  ";; ABI: raw-u64 scalar plus bounded Borsh bytes/String/unsigned-array views.",
  ";; Honesty: deployable=false; no nearcore / near-sandbox / testnet claim."
]

def importModule : String := "env"

end ProofForge.Wasm.Near.Host
